const BORDER = {
  UPDATE: 'UPDATE_BORDER',
  RESET: 'RESET_BORDER',
};

const THRESHOLD = {
  UPDATE: 'UPDATE_THRESHOLD',
  RESET: 'RESET_THRESHOLD',
};

const EDITPEAK = {
  ADDNEGATIVE: 'ADD_TO_NEGATIVE_LIST',
  RMNEGATIVE: 'RM_FROM_NEGATIVE_LIST',
  ADDPOSITIVE: 'ADD_TO_POSITIVE_LIST',
  RMPOSITIVE: 'RM_FROM_POSITIVE_LIST',
};

const STATUS = {
  TOGGLEBTNSAVE: 'TOGGLE_BTN_SAVE',
  TOGGLEBTNWRITE: 'TOGGLE_BTN_WRITE',
  TOGGLEBTNALL: 'TOGGLE_BTN_ALL',
};

const MANAGER = {
  RESETALL: 'RESET_ALL',
  TOGGLEISEDIT: 'TOGGLE_IS_EDIT',
};

const LAYOUT = {
  UPDATE: 'UPDATE_LAYOUT',
};

export {
  BORDER, THRESHOLD, EDITPEAK, STATUS, MANAGER, LAYOUT,
};
