name: E2E Testing
on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run --max_old_space_size=12288 build
          start: npm --max_old_space_size=12288 start
          browser: chrome